server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled=false:

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: project.hotel.pm@gmail.com
    password: bxcsfmtdfgofjpcx
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

logging:
  level:
    com.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
