server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled=false:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB

cloudinary:
  cloudName: dvsrsgf1b
  apiKey: 373982796696613
  apiSecret: -kjrYl0BBLsOitvCcxn5pxrd3Rk

openWeather:
  apiKey: ffbba9b48141d0bdab10f444dfaa2740

logging:
  level:
    com.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
